version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cakephp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=password
    links:
      - db
    ports:
      - 3000:80
    volumes:
      - "./phpmyadmin/sessions:/sessions"
  php:
    build: ./docker/php
    ports:
      - '8080:80'
    volumes: 
      - ./cakephp:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - db